export const BROWSER_AI_STAGE_TIMEOUT_MS = 180_000;
export const BROWSER_AI_REPAIR_TIMEOUT_MS = 180_000;
export const BROWSER_AI_WAIT_CYCLE_MS = 180_000;
export const BROWSER_AI_WAIT_CYCLES_BEFORE_DECISION = 4;
