import { afterEach, describe, expect, test } from 'bun:test';
import { mkdirSync, mkdtempSync, rmSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { dirname, join } from 'node:path';
import {
  requiredAgentsFiles,
  runAgentsInstructionsCheck,
  type ApplyRuler,
} from '../agentsInstructionsCheck';

const roots: string[] = [];
const generated = '<!-- Generated by Ruler -->\n\n\n<!-- Source: .ruler/AGENTS.md -->\n\n# Test rules\n';

function createFixture(trackedRoot = generated): string {
  const root = mkdtempSync(join(tmpdir(), 'agents-check-test-'));
  roots.push(root);
  mkdirSync(join(root, '.ruler'), { recursive: true });
  writeFileSync(join(root, '.ruler', 'AGENTS.md'), '# Test rules\n');
  writeFileSync(join(root, '.ruler', 'ruler.toml'), 'default_agents = ["agentsmd"]\n');
  writeFileSync(join(root, 'AGENTS.md'), trackedRoot);
  return root;
}

const stableApply: ApplyRuler = (projectRoot) => {
  writeFileSync(join(projectRoot, 'AGENTS.md'), generated);
};

function check(root: string, applyRuler: ApplyRuler = stableApply) {
  return runAgentsInstructionsCheck({
    workspaceRoot: root,
    requiredFiles: [],
    requiredLeafFiles: [],
    routedFiles: [],
    verifyTracked: false,
    applyRuler,
  });
}

afterEach(() => {
  while (roots.length > 0) {
    const root = roots.pop();
    if (root) rmSync(root, { recursive: true, force: false });
  }
});

describe('AGENTS/Ruler governance checker', () => {
  test('fails when tracked root drifts from temporary Ruler output', () => {
    const result = check(createFixture('stale root\n'));
    expect(result.ok).toBeFalse();
    expect(result.errors).toContain('临时 Ruler 生成的 AGENTS.md 与 tracked 根文件不一致。');
  });

  test('fails when a second apply changes generated bytes', () => {
    let count = 0;
    const result = check(createFixture(), (projectRoot) => {
      count += 1;
      writeFileSync(join(projectRoot, 'AGENTS.md'), generated.repeat(count));
    });
    expect(result.ok).toBeFalse();
    expect(result.errors.some((error) => error.includes('Ruler 连续 apply 不是字节幂等'))).toBeTrue();
  });

  test('keeps vendored .local AGENTS outside the explicit required list', () => {
    expect(requiredAgentsFiles.map(String).some((path) => path.startsWith('.local/'))).toBeFalse();
    const root = createFixture();
    mkdirSync(join(root, '.local', 'vendor'), { recursive: true });
    writeFileSync(join(root, '.local', 'vendor', 'AGENTS.md'), '# Vendored\n');
    expect(check(root).ok).toBeTrue();
  });

  test.each([
    'packages/ingest-documents/AGENTS.md',
    'packages/blood-hunter-v14/AGENTS.md',
    'foundry-modules/fvtt-blood-hunter-2024/AGENTS.md',
    'foundry-modules/fvtt-babele-rolltable-embed-translation/AGENTS.md',
    'foundry-modules/fvtt-injury-fading-spirits/AGENTS.md',
    'foundry-modules/fvtt-json-forge/AGENTS.md',
    'foundry-modules/fvtt-house-rules/AGENTS.md',
  ])('fails closed when required leaf is missing: %s', (leaf) => {
    const root = createFixture();
    const result = runAgentsInstructionsCheck({
      workspaceRoot: root,
      requiredFiles: [leaf],
      requiredLeafFiles: [],
      routedFiles: [],
      verifyTracked: false,
      applyRuler: stableApply,
    });
    expect(result.ok).toBeFalse();
    expect(result.errors).toContain(`缺少必需说明文件：${leaf}`);
  });

  test('fails when Ruler emits any non-AGENTS artifact', () => {
    const result = check(createFixture(), (projectRoot) => {
      writeFileSync(join(projectRoot, 'AGENTS.md'), generated);
      const extra = join(projectRoot, '.mcp', 'config.json');
      mkdirSync(dirname(extra), { recursive: true });
      writeFileSync(extra, '{}\n');
    });
    expect(result.ok).toBeFalse();
    expect(result.errors.some((error) => error.includes('Ruler 临时输出产生额外产物'))).toBeTrue();
  });
});
