import { existsSync, readFileSync, statSync } from 'node:fs';
import { dirname, join, relative, resolve, sep } from 'node:path';

const workspaceRoot = resolve(import.meta.dir, '..', '..');
const rootAgentsPath = join(workspaceRoot, 'AGENTS.md');
const rulerSourcePath = join(workspaceRoot, '.ruler', 'AGENTS.md');
const generatedHeader = '<!-- Generated by Ruler -->\n\n\n<!-- Source: .ruler/AGENTS.md -->\n\n';
const maxInstructionChainBytes = 32 * 1024;

const requiredAgentsFiles = [
  'AGENTS.md',
  'packages/AGENTS.md',
  'packages/parser/AGENTS.md',
  'packages/generation/AGENTS.md',
  'packages/workflows/AGENTS.md',
  'packages/intake-ai/AGENTS.md',
  'packages/ingest-plaintext/AGENTS.md',
  'packages/crawl-goddessfantasy/AGENTS.md',
  'packages/assets-icons/AGENTS.md',
  'packages/spell-manifest-contracts/AGENTS.md',
  'apps/AGENTS.md',
  'apps/cli/AGENTS.md',
  'apps/web/AGENTS.md',
  'foundry-modules/AGENTS.md',
  'foundry-modules/chat-memory-guard/AGENTS.md',
  'foundry-modules/session-monitor/AGENTS.md',
  'tools/AGENTS.md',
  'tools/foundry-ops/AGENTS.md',
  'foundry-modules/monster-spell-resolver/AGENTS.md',
] as const;

const routedFromRoot = [
  'packages/AGENTS.md',
  'apps/AGENTS.md',
  'foundry-modules/AGENTS.md',
  'tools/AGENTS.md',
  'foundry-modules/monster-spell-resolver/AGENTS.md',
] as const;

const leafScopes = requiredAgentsFiles
  .filter((path) => path !== 'AGENTS.md' && !['packages/AGENTS.md', 'apps/AGENTS.md', 'foundry-modules/AGENTS.md', 'tools/AGENTS.md'].includes(path))
  .map((path) => dirname(path));

const errors: string[] = [];

function normalize(text: string): string {
  return text.replace(/\r\n/g, '\n').trimEnd();
}

function readWorkspaceFile(path: string): string {
  return readFileSync(join(workspaceRoot, path), 'utf8');
}

if (!existsSync(rulerSourcePath)) {
  errors.push('缺少根说明源文件 .ruler/AGENTS.md。');
} else if (!existsSync(rootAgentsPath)) {
  errors.push('缺少生成后的根 AGENTS.md。');
} else {
  const expectedRoot = generatedHeader + normalize(readFileSync(rulerSourcePath, 'utf8'));
  const actualRoot = normalize(readFileSync(rootAgentsPath, 'utf8'));
  if (actualRoot !== expectedRoot) {
    errors.push('根 AGENTS.md 与 .ruler/AGENTS.md 的规范生成结果不一致。请修改源文件并重新生成根文件。');
  }
}

for (const path of requiredAgentsFiles) {
  const absolutePath = join(workspaceRoot, path);
  if (!existsSync(absolutePath) || !statSync(absolutePath).isFile()) {
    errors.push(`缺少必需说明文件：${path}`);
    continue;
  }

  if (path !== 'AGENTS.md') {
    const content = readWorkspaceFile(path);
    if (!content.includes('这个功能是做什么的') && !content.includes('这层目录是做什么的')) {
      errors.push(`${path} 缺少面向人的功能说明。`);
    }
    if (!content.includes('完成标准')) {
      errors.push(`${path} 缺少完成标准。`);
    }

    const scopeDirectory = join(workspaceRoot, dirname(path));
    if (!existsSync(scopeDirectory) || !statSync(scopeDirectory).isDirectory()) {
      errors.push(`${path} 对应的功能目录不存在：${relative(workspaceRoot, scopeDirectory)}`);
    }
  }
}

if (existsSync(rootAgentsPath)) {
  const rootContent = readFileSync(rootAgentsPath, 'utf8');
  for (const route of routedFromRoot) {
    if (!rootContent.includes(route)) {
      errors.push(`根 AGENTS.md 没有路由到 ${route}。`);
    }
  }
}

const retiredGeneratorAgents = join(workspaceRoot, 'src', 'core', 'generator', 'AGENTS.md');
if (existsSync(retiredGeneratorAgents)) {
  errors.push('旧 src/core/generator/AGENTS.md 仍存在，会与 packages/generation/AGENTS.md 形成重复 owner。');
}

const retiredSpellResolverRoot = join(workspaceRoot, 'src', 'foundry', 'monster-spell-resolver');
if (existsSync(retiredSpellResolverRoot)) {
  errors.push('旧 src/foundry/monster-spell-resolver 仍存在，会与 foundry-modules/monster-spell-resolver 形成重复 owner。');
}

for (const leafScope of leafScopes) {
  const segments = leafScope.split('/');
  const chain = ['AGENTS.md'];
  let current = workspaceRoot;
  for (const segment of segments) {
    current = join(current, segment);
    const candidate = join(current, 'AGENTS.md');
    if (existsSync(candidate)) chain.push(relative(workspaceRoot, candidate).split(sep).join('/'));
  }

  const chainBytes = chain.reduce((sum, path) => sum + Buffer.byteLength(readWorkspaceFile(path), 'utf8'), 0);
  if (chainBytes > maxInstructionChainBytes) {
    errors.push(`${leafScope} 的 AGENTS 指令链为 ${chainBytes} bytes，超过默认 32 KiB：${chain.join(' -> ')}`);
  }
}

if (errors.length > 0) {
  console.error('AGENTS.md 分层检查失败：');
  for (const error of errors) console.error(`- ${error}`);
  process.exitCode = 1;
} else {
  console.log(`AGENTS.md 分层检查通过：${requiredAgentsFiles.length} 个必需文件，所有根路由和指令链均有效。`);
}
