import { readFileSync, writeFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { Command } from 'commander';
import type { MonsterIntakeIR } from '@fvtt-json-generator/intake-ai/types';
import {
  renderIntakeVerificationMarkdown,
  verifyMonsterIntake,
} from '@fvtt-json-generator/intake-ai/verifier';

export function verifyIntakeFiles(options: {
  sourcePath: string;
  irPath: string;
  markdownPath: string;
  actorPath: string;
  jsonOutput?: string;
  markdownOutput?: string;
}) {
  const source = readFileSync(resolve(options.sourcePath), 'utf-8');
  const ir = JSON.parse(readFileSync(resolve(options.irPath), 'utf-8')) as MonsterIntakeIR;
  const markdown = readFileSync(resolve(options.markdownPath), 'utf-8');
  const actor = JSON.parse(readFileSync(resolve(options.actorPath), 'utf-8')) as unknown;
  const report = verifyMonsterIntake(source, ir, markdown, actor, inferIntakeCoverageRange(ir));
  if (options.jsonOutput) writeFileSync(resolve(options.jsonOutput), JSON.stringify(report, null, 2));
  if (options.markdownOutput) writeFileSync(resolve(options.markdownOutput), renderIntakeVerificationMarkdown(report));
  return report;
}

export function inferIntakeCoverageRange(ir: MonsterIntakeIR): { start: number; end: number } | undefined {
  const ranges = ir.coverage.filter((entry) => (
    Number.isInteger(entry.start)
    && Number.isInteger(entry.end)
    && entry.start >= 0
    && entry.end >= entry.start
  ));
  if (ranges.length === 0) return undefined;
  return {
    start: Math.min(...ranges.map((entry) => entry.start)),
    end: Math.max(...ranges.map((entry) => entry.end)),
  };
}

if (import.meta.main) {
  const program = new Command()
    .name('verify:intake')
    .requiredOption('--source <path>', 'Original TXT/Markdown source')
    .requiredOption('--ir <path>', 'MonsterIntakeIR JSON')
    .requiredOption('--markdown <path>', 'Deterministically rendered Markdown')
    .requiredOption('--actor <path>', 'Actor JSON generated by the project workflow')
    .option('--json-output <path>', 'Machine-readable report output')
    .option('--markdown-output <path>', 'Chinese Markdown report output')
    .parse();
  const options = program.opts();
  const report = verifyIntakeFiles({
    sourcePath: options.source,
    irPath: options.ir,
    markdownPath: options.markdown,
    actorPath: options.actor,
    jsonOutput: options.jsonOutput,
    markdownOutput: options.markdownOutput,
  });
  console.log(JSON.stringify(report, null, 2));
  process.exitCode = report.status === 'accepted' ? 0 : 2;
}
